version: "3.9"

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 real_time_crypto_table.asgi:application"
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A real_time_crypto_table worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A real_time_crypto_table beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  static_volume:
